# Site settings
title: Millburn GEMS
email: hello@millburngems.org
description: The official site of Millburn GEMS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://millburngems.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  shannonpeng

# Build settings
markdown: kramdown

permalink:     /news/:year/:month/:day/:title.html
paginate_path: /page-:num
